### ISSUE TITLE
Icons don't display on top menu

### ISSUE THREAD

**Issue by vini59fr** [elax46/custom-brand-icons#118]
Hi there !

I have a bug/issue when using theses icons on the top menu of HA
![2022-01-03 14_50_46-Window](https://user-images.githubusercontent.com/65531566/147938637-1c383478-a4a9-44c6-8206-437639723375.png)
I just have to modify my lovelace and it work

![2022-01-03 14_50_55-Window](https://user-images.githubusercontent.com/65531566/147938832-18a6e362-d0ab-4dcf-9a5f-eb548c856a9e.png)
![2022-01-03 14_51_03-Window](https://user-images.githubusercontent.com/65531566/147938861-7167bedf-460e-4d61-a86f-ac31771fbf3b.png)

But, if I just refesh my browser page (or reload my browser), the icon disappear again

**Comment by elax46** [comment]
Did you follow the[ instructions](https://github.com/elax46/custom-brand-icons#hacs)? It is essential to include this piece of code

  ```yaml
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```
After the change it is necessary to clear the browser cache
