### ISSUE TITLE
Issue related to latest update?

### ISSUE THREAD

**Issue by gabrio79** [elax46/custom-brand-icons#287]
**Describe the bug**
Since latest HA update addon stopped works, I don't see icon now. Nothing changes on my configuration.
Same issue on mobile app

Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest
custom-brand-icons 1.0.86

**Sample of issue**
![image](https://user-images.githubusercontent.com/65911264/205133415-65c32605-8e6c-42f1-8fc4-3d5baa86e8b1.png)
**Sample of used code:**
```
  - entity: light.farmacia_stripled
    name: Stripled
    type: custom:multiple-entity-row
    toggle: true
    state_color: true
    icon: phu:light-strip
    entities:
      - entity: sensor.farmacia_stripled_assorbimento
        name: Assorbimento
  - type: divider
  - entity: light.farmacia_logo_bancone
    name: Logo Bancone
    type: custom:multiple-entity-row
    toggle: true
    state_color: true
    icon: mdi:mortar-pestle-plus
    entities:
      - entity: sensor.farmacia_logo_bancone_assorbimento
        name: Assorbimento
```
