### ISSUE TITLE
no icon - in private mode - after multiple restarts

### ISSUE THREAD

**Issue by aLAN-LDZ** [elax46/custom-brand-icons#357]
hey, I checked the installation even 3 times :P I opened the browser in private mode, even on other device and unfortunately I still don't see the icons :( I installed via hacs

any idea?

config.yaml:

```
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
  themes: !include_dir_merge_named themes
```
```
type: entities
entities:
  - entity: light.lampa
    icon: phu:go
    name: Go
  - entity: light.lampka
    icon: phu:play
    name: play 1
  - entity: light.pasek_led
    icon: phu:play
    name: play 2
show_header_toggle: false
title: Custom brand icons
```
![image](https://user-images.githubusercontent.com/33158372/220196643-da394f6d-c0b4-4f8c-b055-65ec9f09d85c.png)
