### ISSUE TITLE
Icons not showing up in side panel/lovelace

### ISSUE THREAD

**Issue by labaland** [elax46/custom-brand-icons#46]
Hi! I use use the icon "phu:roborock" for my roborock dashboard on the side panel. but it almost never showing up. same on different devices.

![image](https://user-images.githubusercontent.com/20958435/134799471-5e4a5efc-608f-4ab2-ad4f-3cb2e0e12792.png)
![image](https://user-images.githubusercontent.com/20958435/134799481-1cc3da00-ec26-41a7-beb5-919c193035c8.png)

**Comment by elax46** [comment]
Did you follow the[ instructions](https://github.com/elax46/custom-brand-icons#hacs)? It is essential to include this piece of code

  ```yaml
frontend:
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
```
