### ISSUE TITLE
Issue with phu: (same for bha:) icons in HA 2024.3.0

### ISSUE THREAD

**Issue by danielbrunt57** [elax46/custom-brand-icons#589]
**Describe the bug**
None of the phu: icons (same for bha: icons) will display in lovelace dashboard under HA 2024.3.0.

## Don't see the icon?

It's not a caching issue. They just fail to display.

**Comment by danielbrunt57** [comment]
Okay, so I had an idea which worked.  Rather than picking a `phu:` or `bha:` icon in the entity's settings, I added the entries to `customize:` in _configuration.yaml_ to set the icon:

```
light.front_porch_light:
  icon: phu:ceiling-surimu
  
light.landing_2:
  icon: phu:ceiling-adore-alt-flush
```

![image](https://github.com/elax46/custom-brand-icons/assets/49846893/e1fe7ae4-d89d-4616-b937-978f0ab77991)
